### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by davidnewhall** [devopsarr/radarr-go#31]
Hey @Fuochi,

I don't know how else to chat with you, so I'm here. :)

Curious how well this library works? Did you stop using golift starr in favor of auto generated code like this? Looks pretty cool, and I'm intrigued. 

Do you hang out in any of the Discords where I can pick your brain further?

**Comment by Fuochi** [comment]
Hi @davidnewhall,
Yes, I started auto-generating the SDKs 'cause I wanted to move my focus on the terraform provider itself.
The libraries generally work, but they are coupled to the various arr swagger files.
Unfortunately, this has some downside as well. I still need to figure out how to properly manage dependency update, and if I need tests. Also, making a change on the generator has usually a huge impact.

If you want to discuss something, I still am in the golift chit-chat channel, I'll drop out a message later!

**Comment by davidnewhall** [comment]
Good info man! Thanks for the explanation and jumping into the Discord.
